spring:
    application:
      name: mrusnique
    datasource:
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASS}
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
