spring:
    application:
      name: mrusnique
    datasource:
      url: jdbc:postgresql://localhost:5432/mrusnique
      username: postgres
      password: ivanov4231
      driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
